agramlex.lex.gen.o: agrampar.codes.h
agrampar.o: agramlex.lex.gen.h
agrampar.o: agrampar.tab.h
agrampar.o: ast.ast.h
agrampar.tab.o: ast.ast.h
astgen.o: ast.ast.h
example-methods.o: example.ast.gen.h
example-test.o: example.ast.gen.h
gramlex.o: agramlex.lex.gen.h
